version: '3.9'
services:
  api:
    image: ${DOCKER_REGISTRY}/numerology-api-v3:${API_TAG}
    build:
      context: ./numerology-api-v3
      dockerfile: Dockerfile
  
  fe:
    image: ${DOCKER_REGISTRY}/numerology-fe-v3:${FE_TAG}
    build:
      context: ./numerology-fe-v3
      dockerfile: Dockerfile
      args:
        VITE_ENV: ${VITE_ENV}
        VITE_API_URI: ${VITE_API_URI}