apiVersion: apps/v1
kind: Deployment
metadata:
  name: numerology-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: numerology-api
  template:
    metadata:
      labels:
        app: numerology-api
    spec:
      containers:
        - name: numerology-api
          image: longthanhle1122/numerology-api:0d58676
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: numerology-api-secret-vol
              mountPath: /api/.env

      volumes:
        - name: numerology-api-secret-vol
          secret:
            secretName: numerology-api-secret
