name: My Numerology CI
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: Run ID
        required: true
        type: string
      project:
        description: Project
        required: true
        type: choice
        options:
          - fe
          - api

jobs:
  generate-k8s-manifest:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Check run ID
        run: |
          echo "Running on \"${{ inputs.project }}\" project with ID: ${{ inputs.run_id }}"
      - name: Checkout to the source code
        uses: actions/checkout@v4
      - name: Generate K8S Manifest Files
        run: |
          node ./k8s/generate ${{ inputs.project }} ${{ inputs.run_id }}
